name: Generate OpenAPI JSON

on:

  schedule:
    -cron: "0 0 * * *"
  push:
    branches:
      - docs
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Download latest openapi.json
      run: |
        curl -o latest_openapi.json https://rtr-api.gotabi.ai/api-rtr/openapi.json
    
    # 5. Switch to the docs branch
    - name: Checkout the docs branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout docs

    # 6. Copy openapi.json to the docs branch
    - name: Copy openapi.json to the root of the docs branch
      run: |
        git add openapi.json
        git commit -m "Update OpenAPI JSON"
        git push origin docs