name: Generate OpenAPI JSON

on:
  push:
    branches:
      - main
      - test
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v3

    # 2. Set up Python environment
    - name: Install FastAPI and Pydantic
      run: |
          python -m pip install --upgrade pip
          pip install "fastapi[standard]" pydantic

    # 4. Run the Python script to generate the openapi.json file
    - name: Run script.py to generate openapi.json
      run: |
        python script.py

    # 5. Switch to the docs branch
    - name: Checkout the docs branch
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git checkout docs

    # 6. Copy openapi.json to the docs branch
    - name: Copy openapi.json to the root of the docs branch
      run: |
        cp openapi.json ./
        git add openapi.json
        git diff --name-only --cached | grep -v "openapi.json" | xargs git reset
        git commit -m "Update OpenAPI JSON"
        git push origin docs