name: Generate OpenAPI JSON

on:
  push:
    branches:
      - main
      - test
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  generate-openapi:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 2. Set up Python environment
    - name: Install FastAPI and Pydantic
      run: |
          python -m pip install --upgrade pip
          pip install "fastapi[standard]" pydantic

    # 4. Run the Python script to generate the openapi.json file
    - name: Run script.py to generate openapi.json
      run: |
        python script.py
    
    - name: Stash changes
      run: |
        git stash

    # 5. Switch to the docs branch
    - name: Checkout the docs branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout docs

    - name: Apply stashed changes
      run: |
        git stash pop

    # 6. Copy openapi.json to the docs branch
    - name: Copy openapi.json to the root of the docs branch
      run: |
        git add openapi.json
        git commit -m "Update OpenAPI JSON"
        git push origin docs